const ADD_TASK = "ADD_TASK";
const REMOVE_TASK = "REMOVE_TASK";
const ADD_SELECTED_TASK = "ADD_SELECTED_TASK";
const REMOVE_SELECTED_TASK = "REMOVE_SELECTED_TASK";
const REMOVE_GROUP_TASK = "REMOVE_GROUP_TASK";
const EDIT_TASK = "EDIT_TASK";
const EDIT_ONE_TASK = "EDIT_ONE_TASK";
const OPEN_MODAL = "OPEN_MODAL";
const CLOSE_MODAL = "CLOSE_MODAL";
const EMPTY_SELECTED_TASK = "EMPTY_SELECTED_TASK";

export { ADD_TASK, REMOVE_TASK, EDIT_ONE_TASK, ADD_SELECTED_TASK, REMOVE_SELECTED_TASK, REMOVE_GROUP_TASK, EDIT_TASK, OPEN_MODAL, CLOSE_MODAL, EMPTY_SELECTED_TASK };