const ADD_TASK = "ADD_TASK";
const REMOVE_TASK = "REMOVE_TASK";
const ADD_SELECTED_TASK = "ADD_SELECTED_TASK";
const REMOVE_SELECTED_TASK = "REMOVE_SELECTED_TASK";
const REMOVE_GROUP_TASK = "REMOVE_GROUP_TASK";
const EDIT_TASK = "EDIT_TASK";

export { ADD_TASK, REMOVE_TASK, ADD_SELECTED_TASK, REMOVE_SELECTED_TASK, REMOVE_GROUP_TASK, EDIT_TASK };